name: Build Extension Otomatis

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Ambil Components Jar Langsung
      run: |
        mkdir -p lib/app-inventor
        # Link ini menggunakan jalur yang kita temukan di gambar Bapak tadi
        curl -L "https://github.com/mit-cml/appinventor-sources/raw/master/appinventor/lib/appinventor/components.jar" -o lib/app-inventor/components.jar
        
        # Cek apakah file berhasil diambil atau masih kosong
        ls -lh lib/app-inventor/

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Build Extension
      run: ant extensions

    - name: Upload AIX
      uses: actions/upload-artifact@v4
      with:
        name: AndroidID-v1
        path: out/*.aix
